# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u5bf9\u8c61id')),
                ('comment_type', models.IntegerField(choices=[(1, 'CTF\u9898\u76ee'), (2, '\u6f0f\u6d1e\u4f53\u9a8c')], default=1, verbose_name='\u8bc4\u8bba\u7c7b\u578b')),
                ('comments', models.CharField(max_length=300, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bc4\u8bba',
                'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u5bf9\u8c61id')),
                ('fav_type', models.IntegerField(choices=[(1, 'CTF\u9898\u76ee'), (2, '\u6f0f\u6d1e\u4f53\u9a8c')], default=1, verbose_name='\u6536\u85cf\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_id', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u5bf9\u8c61id')),
                ('learn_type', models.IntegerField(choices=[(1, 'CTF\u9898\u76ee'), (2, '\u6f0f\u6d1e\u4f53\u9a8c')], verbose_name='\u5b66\u4e60\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5b66\u4e60',
                'verbose_name_plural': '\u7528\u6237\u5b66\u4e60',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6237id')),
                ('message', models.CharField(default='', max_length=500, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
    ]
